# Jekyll
theme: linkhub-jekyll-theme

# Site Configuration
name: Michael Mondala  # Name of your website
tagline: Links  # Set your preferred page title
description: Passionate about web development, design, and WordPress. Sharing insights, and tutorials.  # Also used as a meta description
favicon: https://picsum.photos/100 # Path / URL to the favicon of your website (e.g., 'assets/images/favicon.png')
logo: assets/images/MikeDP.jpg # Path / URL to the logo (e.g., 'assets/images/logo.png')
url: https://github.com/mijaonline/linkpro # URL of your website
ga4: G-XXXXXXX # Google Analytics 4 measurement ID (optional). Remove it if not needed.
twitter:
  username: username # Used for SEO
  card: summary
image:
  path: https://picsum.photos/200 #Used for SEO
  height: 100
  width: 100
  alt: logo

# Verified Badge Configuration
badge: true  # Set to 'true' or 'false' to enable / disable the badge
icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
color: '#dfb221'  # Define the color of the badge

# Plugins
plugins:
  - jekyll-seo-tag
 
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]